// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LandingForm': string;
  'landing': string;
  'landingContainer': string;
  'landingForm': string;
}
export const cssExports: CssExports;
export default cssExports;
