// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tutorial': string;
  'tutorialModal': string;
}
export const cssExports: CssExports;
export default cssExports;
