// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuncherInfoLeft': string;
  'muncherInfoLeft': string;
}
export const cssExports: CssExports;
export default cssExports;
