// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'GameOverButton': string;
  'GameOverContainer': string;
  'gameOverButton': string;
  'gameOverContainer': string;
  'theContent': string;
}
export const cssExports: CssExports;
export default cssExports;
