// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuncherGame': string;
  'MuncherInfo': string;
  'muncherGame': string;
  'muncherInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
