// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth-form': string;
  'authForm': string;
}
export const cssExports: CssExports;
export default cssExports;
