const newGame = [
  { position: 0, word: 'tree', phonics: 'ee', occupied: null },
  { position: 1, word: 'tree', phonics: 'ee', occupied: null },
  { position: 2, word: 'tree', phonics: 'ee', occupied: null },
  { position: 3, word: 'tree', phonics: 'ee', occupied: null },
  { position: 4, word: 'tree', phonics: 'ee', occupied: null },
  { position: 5, word: 'tree', phonics: 'ee', occupied: null },
  { position: 6, word: 'tree', phonics: 'ee', occupied: null },
  { position: 7, word: 'tree', phonics: 'ee', occupied: null },
  { position: 8, word: 'tree', phonics: 'ee', occupied: null },
  { position: 9, word: 'tree', phonics: 'ee', occupied: null },
  { position: 10, word: 'tree', phonics: 'ee', occupied: null },
  { position: 11, word: 'tree', phonics: 'ee', occupied: null },
  { position: 12, word: 'tree', phonics: 'ee', occupied: null },
  { position: 13, word: 'tree', phonics: 'ee', occupied: null },
  { position: 14, word: 'tree', phonics: 'ee', occupied: null },
  { position: 15, word: 'tree', phonics: 'ee', occupied: null },
  { position: 16, word: 'tree', phonics: 'ee', occupied: null },
  { position: 17, word: 'tree', phonics: 'ee', occupied: null },
  { position: 18, word: 'tree', phonics: 'ee', occupied: null },
  { position: 19, word: 'tree', phonics: 'ee', occupied: null },
  { position: 20, word: 'tree', phonics: 'ee', occupied: null },
  { position: 21, word: 'tree', phonics: 'ee', occupied: null },
  { position: 22, word: 'tree', phonics: 'ee', occupied: null },
  { position: 23, word: 'tree', phonics: 'ee', occupied: null },
  { position: 24, word: 'tree', phonics: 'ee', occupied: null },
  { position: 25, word: 'tree', phonics: 'ee', occupied: null },
  { position: 26, word: 'tree', phonics: 'ee', occupied: null },
  { position: 27, word: 'tree', phonics: 'ee', occupied: null },
  { position: 28, word: 'tree', phonics: 'ee', occupied: null },
  { position: 29, word: 'tree', phonics: 'ee', occupied: null },
  { position: 30, word: 'tree', phonics: 'ee', occupied: null },
  { position: 31, word: 'tree', phonics: 'ee', occupied: null },
  { position: 32, word: 'tree', phonics: 'ee', occupied: null },
  { position: 33, word: 'tree', phonics: 'ee', occupied: null },
  { position: 34, word: 'tree', phonics: 'ee', occupied: null },
  { position: 35, word: 'seal', phonics: 'ea', occupied: null },
];

const targets = ['ee', 'ea', 'oo', 'ou'];

export default newGame;
