// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'mulShdSpin': string;
}
export const cssExports: CssExports;
export default cssExports;
